### ISSUE TITLE
General code review and an alternative implementation

### ISSUE THREAD

**Issue by burdoto** [sj14/retry#2]
https://github.com/sj14/retry/blob/1c0275b650db3772bd678508536592c9f09a137d/src/main/java/com/github/sj14/retry/Retry.java#L47

Hey, I've seen you tried out some Java things. I've taken a look at your code and I would suggest you used the method `Class#isAssignableFrom(Class)` to check for types. This methods parameter will be your variable type, the class you call it on should be the whitelist type you want to check for.

**Comment by sj14** [comment]
Thanks a lot for the suggestion! 🎉
When I understand it correctly, this change enables to whitelist a whole set of classes (as all subclasses are automatically whitelisted too).
The issue I see here is, that it might whitelist more classes than anticipated. How should I say whitelist class `x` and all subclasses (`x.a` ... ` x.z`) except its subclasses `x.x` and `x.y`. I guess another parameter, e.g. `blacklist` might solve this.
On the other hand, when a new subclass from an already whitelisted class is created, it is automatically whitelisted, which might be desired or not. In general, I would prefer to be a bit stricter and adding an additional whitelisted class explicitly instead of letting one class slip through the check accidentally.
What do you think?

**Comment by burdoto** [comment]
You could circumvent this with annotations for example, e. G. In a case where you whitelist all `IOException`s but you might want to blacklist `SocketException`, so you could annotate the method invocation with like `@ExceptionBlacklist(SocketException.class)` and then reflectively scan for this annotation.
If this change is too much for you, I can open a PR about it tomorrow.

**Comment by burdoto** [comment]
Such annotation could also be placed on a `RetryAction` implementation

**Comment by sj14** [comment]
Thanks a lot, I really appreciate your help! I'm just trying to figure out the scale of the issue before you put any work into it.
The current implementation wouldn't be as satisfying as you have to whitelist too many classes, right? Can you share a bit more about the use case you have?
What do you think about the concerns I expressed?

> On the other hand, when a new subclass from an already whitelisted class is created, it is automatically whitelisted, which might be desired or not. In general, I would prefer to be a bit stricter and adding an additional whitelisted class explicitly instead of letting one class slip through the check accidentally.

**Comment by burdoto** [comment]
Hi, sorry for not responding earlier.

I have rewritten your library as an example on how I personally would have done it.
I have also heavily documented the library now, to help you understand my thinking. However, this is another way to do it, and not a guideline on "how to do it".

You can find my version of it [on my fork](https://github.com/burdoto/retry/tree/remove-duplicate-methods).
Hope you can understand my thinking.

You should also take a look at the commit history. I have spotted a small set of mistakes and inconveniences, and I have tried to fix them as helpful as possible. I hope this can help you!

**Comment by sj14** [comment]
Thanks for the work. You seem to have solid Java experience and there are things I will pick up such as using `Collection` instead of `List`, the private constructor, and how to do better documentation ;-).

On the other hand, there are changes which I will probably not merge or adapt.
- The tests look like they are not actually testing the business logic.
- The removal of the `onException`/`onThrowable` distinction. For me, this is an important feature because, in production code, I don't want to catch `java.lang.Error`s, only Exceptions, whereas I sometimes want to catch Errors in testing code. But I agree, there is too much duplicate code ;-)
- The downgrade of Junit from 5 to 4.

If those changes are important for you, I guess your own library or permanent fork will be the better solution. But again, thanks a lot for the work and as said, I will definitely adopt or cherry-pick some things.

**Comment by burdoto** [comment]
The tests are solid towards expected behavior of the library, and the JUnit downgrade was a personal choice of mine.
In my opinion, there is absolutely no reason to have `onException` at all, plus the method names are very confusing.

**Comment by burdoto** [comment]
Afeer all, this was just an idea of mine, and of course you don't need to adapt to it. I just tried to prove another different way of solving it, since it looked like you just started with Java.

**Comment by sj14** [comment]
Of course, it's always a good idea to see how other people would approach the same problem. I've already cherry-picked one of your commits and gave a bit more feedback to the tests (also the whitelist approach changed and so I had a mistake in my mind). Thanks for your work 🎉

**Comment by burdoto** [comment]
By the way:
On my fork, whitelisting `java.lang.Error.class` is effectively the same as having the duplicates, because a `Class#isInstanceOf(Object)` is used. This also checks for implementation extension.

**Comment by sj14** [comment]
Wow, this is a very good hint. This might solve my code duplicate issues :+1:

**Comment by burdoto** [comment]
I'd suggest you still use a facade method, but you should definitely reconsider your naming scheme, as your current naming decision suggests some kind of listener action, but rather than just the class but also the method name should consider what the facade method does.

**Comment by sj14** [comment]
What would you suggest?

**Comment by burdoto** [comment]
Something like `Retry#retryWithoutErrors` and `Retry#retryInfinitelyWithoutErrors` idk
